### ISSUE TITLE
unable to see the orders, unauthorized error message

### ISSUE THREAD

**Issue by abbasali-io** [abbasali-io/tdp-global#21]
while getting order details by order number, 401 error is encountered as the API is called.

the error on the device
<img width="366" alt="image" src="https://github.com/abbasali-io/tdp-global/assets/3590177/caea3fd7-befe-4c9b-82d9-1ef76cb55e57">

The error on the API call below

<img width="424" alt="image" src="https://github.com/abbasali-io/tdp-global/assets/3590177/5526f351-0a18-4a75-9060-36c107be8693">

**Comment by abbasali-io** [comment]
@mohsinnaeem21 @Rahbul 

We noticed that apart from the search api, this is consistent behaviour across all other APIs. below is the response that we are getting.

<img width="355" alt="image" src="https://github.com/abbasali-io/tdp-global/assets/3590177/c4c353bc-5d90-4ced-9ca2-d289a5e9398b">

**Comment by Rahbul** [comment]
I create the same senario on my side this is because you didn't pass the bearer token on header 
![Get-Single-Online-Order-by-order-Number-My-Workspace](https://github.com/abbasali-io/tdp-global/assets/157615726/2e7801f6-4098-4e81-a97b-4b558f235bd2)

I use the bearer token on header then response is:
 
![Get-Single-Online-Order-by-order-Number-My-Workspace (1)](https://github.com/abbasali-io/tdp-global/assets/157615726/4dd460a5-4aae-48d4-85b3-49a0d6f120de)

**Comment by abbasali-io** [comment]
@Rahbul I AM using the Auth Token for this API as well, the auth token is set in the application preferences, if it is not set properly, NONE of the API would work. 

moreover, we are not having this issue from Postman, but from calling the API from a web server, as you may see, we have the test server at heroku platform to conduct API tests!

kindly advise.

**Comment by Rahbul** [comment]
Please make a cURL request to the API to retrieve the data from the browser, as discussed with @mohsinnaeem21 bhai.

**Comment by abbasali-io** [comment]
the apps cannot make cURL request

**Comment by abbasali-io** [comment]
We just discussed with @mohsinnaeem21 bhai, he is looking into the resolution on why some of the APIs are giving 401 unauthorized status error.

**Comment by abbasali-io** [comment]
closing as no fixed
